### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by brendon** [lassebunk/gretel#100]
Hi @WilHall, I'm just looking at using `gretel` in a new project and just wanted to check in on whether you're still actively maintaining it? Thanks for merging in my PR from ages ago. For some reason I don't think I noticed that it happened :)

**Comment by gurgeous** [comment]
I share this concern. I added gretel to a new project and it worked well, but we had a long debate internally about whether to adopt a project that appears to be abandoned. I suppose we can always maintain our own branch if necessary.

**Comment by WilHall** [comment]
@brendon @gurgeous I am looking for people to help maintain this gem. @MrShemek has offered at one point, and the plan was to continue development at [WilHall/gretel](https://github.com/WilHall/gretel).

If either of you are interested in helping out, or know anyone who is interested, I'm happy to help set that up. I just haven't had the bandwidth myself to devote to reviving development on the gem.

**Comment by MrShemek** [comment]
Hi guys, as @WilHall mentioned, I will help him maintaining this project. I should have time on Sunday, so I will review existing issues and move them to the new repository ([WilHall/gretel](https://github.com/WilHall/gretel)).

**Comment by gurgeous** [comment]
I don't want to stress anyone out! I know firsthand the perils of being an open source maintainer. I'm personally hesitant to make that kind of commitment after some previous experiences. Some suggestions for reducing stress:

- close issues > 6 months old liberally
- accept PRs liberally
- add contributors liberally

I will certainly pitch in where I can. Perhaps starting with a PR for #103...

**Comment by brendon** [comment]
As an aside, I ended up using https://github.com/piotrmurach/loaf for my project, though I do use `Gretel` in another project still.

**Comment by gurgeous** [comment]
BTW, gretel is a neat gem and definitely worth pushing forward. I appreciate the hard work of everyone involved!

**Comment by MrShemek** [comment]
@brendon according to [rubygem](https://rubygems.org/gems/gretel/versions/3.0.9) @WilHall has owner rights so it should not be a problem.

**Comment by WilHall** [comment]
Hey all,

Thank you so much for your patience. @MrShemek and I are starting the migration of issues and development to [WilHall/gretel](https://github.com/WilHall/gretel) - so please tune in there, and let us know if you'd like to help out :)
