### ISSUE TITLE
Add a screenshot of a generated breadcrumb to the README.md

### ISSUE THREAD

**Issue by oystersauce8** [lassebunk/gretel#101]
it would be nice it include a screenshot of a breadcrumb

I am specially curious how the bootstrap style comes out.

**Comment by MrShemek** [comment]
This is how it looks in one of the apps I'm working on:

![screenshot 2018-06-21 20 16 49](https://user-images.githubusercontent.com/2658237/41737647-2c47b046-7590-11e8-98fa-8b69e5eb2cd8.png)

**Comment by WilHall** [comment]
We will be adding screenshots and an example application in the future at [WilHall/gretel](https://github.com/WilHall/gretel)
