### ISSUE TITLE
Nullable parent for specific crumb

### ISSUE THREAD

**Issue by serghei-topor** [lassebunk/gretel#102]
IMHO it could be useful to have no parent for particular crumb. Be very appreciated for feature.
Thanks in advance!

**Comment by MrShemek** [comment]
Can you please give me an example? I think it might be implemented without changing gem's code.

**Comment by serghei-topor** [comment]
I have:
```
crumb :root do
	link "My Site"
end
crumb :admin_tools do
	link "Admin"
end
crumb :admin_geography do
	link 'Geography'
	parent :admin_tools
end
crumb :admin_geography_regions do
	link 'Regions'
	parent :admin_geography
end
```
and instruction
```
<%= breadcrumb :admin_geography_regions %>
```
generates
**_My Site > Admin > Geography > Regions_**

What I'd like to have is to change crumb :admin_tools
```
crumb :admin_tools do
	link "Admin"
        parent: nil
end
```
and get
**_Admin > Geography > Regions_**

If I set **parent** to **nil** I will get the following exception
![screenshot from 2018-08-13 14 12 22](https://user-images.githubusercontent.com/1078082/44028697-603c7f98-9f03-11e8-817e-46f7ccdceaf4.png)

Thanks!

**Comment by MrShemek** [comment]
It looks like you would like to use `:admin_tools` as a root crumb in given case. If so, then it is easy to achieve:

```
crumb :root do
        return link("My Site") if SOMETHING #for example unless request.params.fetch(:subdomain).eql?('admin')
        link 'Admin'
end

crumb :admin_geography do
	link 'Geography'
end

crumb :admin_geography_regions do
	link 'Regions'
	parent :admin_geography
end
```

Will that work for you?

**Comment by serghei-topor** [comment]
Yeah, I agree with you, I had already implemented the similar logic in my functionality. My proposal is just from the list of nice to have features. It would be great if it's implementable, if not - it's not a big deal to write a custom solution like you proposed. Thanks

**Comment by MrShemek** [comment]
The issue was moved to the new repository: [link](https://github.com/WilHall/gretel/issues/12)
