### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by gurgeous** [lassebunk/gretel#103]
Can we add support for Bootstrap 4? It formats breadcrumbs like so (see below). The tricky part is the requirement for `breadcrumb-item`. Perhaps we need to add a `fragment_class` option for styles? https://getbootstrap.com/docs/4.0/components/breadcrumb/

```html
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="...">Home</a></li>
  <li class="breadcrumb-item"><a href="...">Library</a></li>
  <li class="breadcrumb-item active">Data</li>
</ol>
```

Note for fellow gretel lovers - you can fake bootstrap4-style breadcrumbs using:

```haml
= breadcrumb(separator: nil)
```

along with:

```sass
.breadcrumbs {
  a::after {
    display: inline-block;
    padding: 0 $breadcrumb-item-padding;
    color: $breadcrumb-divider-color;
    content: $breadcrumb-divider;
  }

  .current {
    color: $breadcrumb-active-color;
  }
}
```

**Comment by MrShemek** [comment]
There is a [pull request](https://github.com/WilHall/gretel/pull/1) for it already. I will double check it during the weekend and merge if everything is fine.

**Comment by gurgeous** [comment]
Ah, thank you. Closing!
