### ISSUE TITLE
is this thread-safe?

### ISSUE THREAD

**Issue by silva96** [lassebunk/gretel#104]
we have a table with thousand cities for a city directory and for each of them we instantiate a crum in `config/breadcrumbs.rb` and also we have some other crumbs like this

```ruby
crumb :help_cancel_tickets do
    link t("help.menu.help_cancel_tickets"), help_cancel_tickets_path
    parent :help
  end
```

Then we call it in the view:

```ruby
<% breadcrumb :help_cancel_tickets %>

...
#in the layout
<%= breadcrumbs separator: " &rsaquo; " %>
```

We were using Puma with 4 workers and 4 threads and sometimes we had 
`ActionView::Template::Error: Breadcrumb :help_cancel_tickets not found.` error

But now we increased to 16 threads and errors like this are much more common, why does this happen? I presume 2 possible things:

- all crumbs are initialized in the first thread so when a request lands in another thread, they dont exist in the thread memory?
- Each thread creates in memory their own set of crumbs configured in breadcrumbs.rb but because there are so many, sometimes a request can be processed before all crumbs are in memory?

any thoughts?

**Comment by silva96** [comment]
@WilHall @lassebunk any thoughts?

**Comment by WilHall** [comment]
Hi @silva96, @MrShemek and I are in the process of resurrecting this gem over at [WilHall/gretel](https://github.com/WilHall/gretel). We'll be moving this issue there, and once we get some bookkeeping out of the way we can look into this.

Thanks for your patience

**Comment by silva96** [comment]
OK thanks, For now I added a bunch of begin / rescue in the views.

**Comment by MrShemek** [comment]
The issue was moved to the new repository: [link](https://github.com/WilHall/gretel/issues/13)
