### ISSUE TITLE
View helper generating String instead of HTML

### ISSUE THREAD

**Issue by geekvijay** [lassebunk/gretel#35]
```
<%= breadcrumbs %>
```

is generating 

```
"<div class="breadcrumbs"></div>"
```

instead

```
<div class="breadcrumbs"></div>
```

**Comment by mvladimirovic** [comment]
I can actually confirm this behavior. And for me it is related to using a different development environment name. development works fine development_sandbox does escapes the html.

**Comment by jclusso** [comment]
@mvladimirovic I see the same thing in my staging environment. has anyone found a solution?

**Comment by delphaber** [comment]
Same here. Working on development but on on staging, production rails environment

**Comment by delphaber** [comment]
btw ````== breadcrumbs``` is working
