### ISSUE TITLE
Namespaced breadcrumbs

### ISSUE THREAD

**Issue by BrokenChair** [lassebunk/gretel#48]
Hello, 

I have a site with 2 distinct areas, (public and admin). Both areas can access the same model, for example Posts. So, I created 2 breadcrumb files, public.rb and admin.rb. When rendering in the admin section, I only want the admin.rb breadcrumbs to be loaded.

Since both sections have a :new_post crumb, the pathing doesn't work as expected. Is this possible, or do I have to give namespaced names to each crumb, such as :new_admin_post?

**Comment by batamire** [comment]
+1

**Comment by jimmykarily** [comment]
I would also like to see this implemented. I have the same problem.

**Comment by dminchev** [comment]
+1

**Comment by WilHall** [comment]
Hi @BrokenChair, you are correct - currently you would need to namespace the breadcrumb names yourself. The ability to have separate breadcrumb files is for organizational purposes only.

I'm labelling this as `feature`.

**Comment by shlima** [comment]
+ 1

**Comment by morgant** [comment]
+1

**Comment by MrShemek** [comment]
Issue was moved to the new repository: [link](https://github.com/WilHall/gretel/issues/4)
