### ISSUE TITLE
Breadcrumbs not loading for root path until user visits a nested route

### ISSUE THREAD

**Issue by danielbonnell** [lassebunk/gretel#49]
Hello,

I'm having an issue where the breadcrumbs will not render for the root path the first time a user visits my app until that user visits a nested route. Once the user visits a nested route, the crumbs will load on the root path. I have `display_single_fragment: true` in my layout file. The issue can't be replicated by clearing the cache. It can only be replicated by restarting the server or visiting the app from a different machine. It appears to happen regardless of which browser I use.

Thanks!

**Comment by mmatviyiv** [comment]
Greetings,

You can add this line under ```breadcrumbs``` call
```
breadcrumb :root unless breadcrumbs.links.any?
```

**Comment by WilHall** [comment]
Hi @danielbonnell, if you are still having this issue could you please provide some more information about your environment? E.g. Rails and Gretel version, your `config/breadcrumbs.rb` file, and relevant lines from your `routes.rb` file?

Thanks!

**Comment by danielbonnell** [comment]
@WilHall I had this issue on a pet project I was working on but I haven't touched it since last February and likely won't do anything with it again. The source for the project is [here](https://github.com/danielbonnell/abhnation-rails) if you're still interested.
