### ISSUE TITLE
Slim/haml support ? Breadcrumbs don't display

### ISSUE THREAD

**Issue by benoitr** [lassebunk/gretel#51]
It seems there is an issue using slim (my case) or haml (please see the following links below) to display the breadcrumbs rendered.

http://stackoverflow.com/questions/21946362/rails-gretel-not-rendering
http://stackoverflow.com/questions/18003344/make-breadcrumb-with-gretel-in-rails

Not sure it is effectively related to these template engines but didn't find how to debug it.

**Comment by futhr** [comment]
Hi @benoitr, I use slim for the template parts and have no issues with it.

Examples:

```slim
= raw breadcrumbs style: :bootstrap, display_single_fragment: true
```

```slim
- breadcrumbs(style: :bootstrap, display_single_fragment: true, autoroot: false).tap do |links|
  - links.to_a.each_with_index do |link, index|
    - if index == 0
      - content_for(:header_summary) do
        small= link.text
    - else
      - content_for(:header_nav) do
        li= link_to_if link.url, link.text, link.url
```

**Comment by benoitr** [comment]
Get it! Thanks so much!!
