### ISSUE TITLE
Set default style?

### ISSUE THREAD

**Issue by aried3r** [lassebunk/gretel#53]
Can I set a default style for breadcrumbs somehow in `config/breadcrumbs.rb` or do I have to manually set it every time? I couldn't find a way in the README or the code.

**Comment by futhr** [comment]
`.breadcrumbs` might be a good starting point.

**Comment by aried3r** [comment]
Thanks for your reply, however I could not find a way to set a default style for everytime I call `<%= breadcrums :my_crumb %>`, could you point out what exactly you meant?

**Comment by WilHall** [comment]
Hi @aried3r - Do you mean the Gretel [:style](https://github.com/lassebunk/gretel#styles) option?

This option defaults to `:inline`, and currently there is not a way to set a different default globally.

**Comment by aried3r** [comment]
Thanks for the reply!
Good to see this project alive :)

**Comment by darrennix** [comment]
I have been trying to override DEFAULT_OPTIONS by adding this to the top of breadcrumbs.rb
```
Gretel::Renderer.register_style(:link_current, true)
```
but then realized this is an OPTION not a STYLE and .register_option is not valid.    How can I set the default rendered to use link_current=true without appending that manually to every <% breadcrumb %> ?

**Comment by WilHall** [comment]
@darrennix: Currently, there is no way to modify the default options or styles for Gretel. They must be explicitly passed in.

**Comment by MrShemek** [comment]
Issue was moved to the new repository: [link](https://github.com/WilHall/gretel/issues/5)
