### ISSUE TITLE
Gretel in non-restful routes

### ISSUE THREAD

**Issue by cabaret** [lassebunk/gretel#54]
Hi,

Thanks for the gem. I have been trying to use it with non restful routes and I cant seem to get it working. Mind having a look?

Config file:

    crumb :root do
      link "Home", root_path
    end

    crumb :products do
      link "Products", products_path
      parent :root
    end

    crumb :product_group do
      link product_group.name, root_path # test
      parent :products
    end

I have these routes:

    get "products"                         => "products#index",  as: "products"
    get "products/:group"                  => "products#group",  as: "product_group"
    get "products/:group/:family"          => "products#family", as: "product_family"
    get "products/:group/(:family)/:range" => "products#range",  as: "product_range"

When I do the following in `products/index.haml`, it works fine:

    - breadcrumb :products
    = breadcrumbs

Renders 'Home > Products'

However, when I try this in `products/group.haml`, I get an error about `:product` missing.

`- breadcrumb @product_group`

`Breadcrumb :product not found.`

I don't have a `:product` resource, I have groups, families and ranges. Can't I create more or less custom breadcrumbs?

**Comment by WilHall** [comment]
Hi @cabaret,

I think there is just a misunderstanding about how to pass resources into your custom breadcrumbs. There is an example of accomplishing what you're trying to do in the `README`, but here is an example with your `:product_group` breadcrumb:

*config/breadcrumbs.rb*:
```
crumb :product_group do |product_group|
  link product_group.name, root_path # test
  parent :products
end
```

*products/group.haml*:
```
- breadcrumb :product_group, @product_group
```

The key difference in the examples I provided is that your argument to `breadcrumb` is a **symbol that matches the `crumb` name**, and that `crumb` takes a block which accepts arguments. You pass one or more arguments *after* the first parameter to `breadcrumb`.
