### ISSUE TITLE
Problem with production

### ISSUE THREAD

**Issue by dawidof** [lassebunk/gretel#60]
In development everything is great, but in production it shows 
```html
<ol class="hbreadcrumb breadcrumb"><li><a href="/dashboard">Dashboard</a></li><li><a href="/dashboard/orders">Orders</a></li><li class="current">Order #2</li></ol>
```

It shows like a html code, not like links.

**Comment by madeinussr** [comment]
Had the same problem. If you use some template engine. I use slim, it escapes html by [default](http://www.rubydoc.info/gems/slim/frames#Output_without_HTML_escaping___) I think gretel should deal with it and make something like `html_safe` after rendering.

**Comment by dawidof** [comment]
just add before breadcrumb
```= raw ```

**Comment by WilHall** [comment]
@dawidof, @madeinussr thanks for the report. I'll close this since it doesn't appear to be a Gretel issue.
