### ISSUE TITLE
using jRuby yields uninitialized constant error

### ISSUE THREAD

**Issue by schugabe** [lassebunk/gretel#68]
When running rails 4.2.6 and gretel 3.0.8 on jRuby 9.1.0.0 it yields the following error:

> uninitialized constant error Rails::Application::Railties not found

 when the view helper <%= breadcrumbs style: :bootstrap %> is called.

Replacing https://github.com/lassebunk/gretel/blob/master/lib/gretel.rb#L19 with the following code resolves the issue:

`engines = Rails::Engine::Railties.respond_to?(:engines) ? Rails::Engine::Railties.engines : Rails::Engine.subclasses.map(&:instance)`

**Comment by WilHall** [comment]
This will be fixed by #50
