### ISSUE TITLE
Using tap instead breadcrumbs blocks

### ISSUE THREAD

**Issue by BrunoQuaresma** [lassebunk/gretel#69]
It works 

```
breadcrumbs(display_single_fragment: true) do |links|
      react_component(BREADCRUMBS_COMPONENT, props: { links: links.to_a })
    end
```

But show this message:

```
[Gretel] Calling `breadcrumbs` with a block has been deprecated and will be removed in Gretel version 4.0. Please use `tap` instead. Example:
breadcrumbs(autoroot: false).tap do |links|
     if links.any?
       # process links here
    end
end
```

When i change to tap... not works

```
breadcrumbs(autoroot: false, display_single_fragment: true).tap do |links|
      react_component(BREADCRUMBS_COMPONENT, props: { links: links.to_a })
    end
```

**Comment by WilHall** [comment]
Hello @BrunoQuaresma, what about your second example using `.tap` is not working?

In my testing, I get the same result for `links` when using `.tap` as I do when accessing the breadcrumbs with the deprecated method of using a block.

You should be getting back a `Gretel::Renderer::LinkCollection` (which may be cast to an array using `.to_a` as you are doing), which contains `Gretel::Link` objects; this is the result I am seeing.

Are you seeing a different value for `links` when you use `.tap`?

Thanks

**Comment by BrunoQuaresma** [comment]
@WilHall instead shows the react component it shows the string "User > Apps ..."

**Comment by WilHall** [comment]
@BrunoQuaresma That sounds like an issue with the react component you're using with the `react_component` view helper, not a Gretel issue.

Are you certain that the behavior is different when you use a block versus `.tap`? I don't think anything in Gretel could cause this, since the value of `links` is the same in both examples.

**Comment by kuboon** [comment]
I think this will work:

```ruby
breadcrumbs(autoroot: false, display_single_fragment: true).tap do |links|
  break react_component(BREADCRUMBS_COMPONENT, props: { links: links.to_a })
end
```

``tap`` do nothing without explicit break.

```ruby
puts 3.tap{ 4 }
=> 3
puts 3.tap{ break 4 }
=> 4
```
