### ISSUE TITLE
breadcrumbs not accepting any arguments

### ISSUE THREAD

**Issue by smaziano** [lassebunk/gretel#74]
Hello,

The main method used in the layouts as per exemple:
`<%= breadcrumbs pretext: "You're here: " %>`

isn't accepting any arguments and gives the error:

`wrong number of arguments (given 1, expected 0)
`
If you don't pass any argument the return is empty:
[]

Regards,
Sergio Maziano

**Comment by alexandru-paduraru** [comment]
@smaziano any news on this?

**Comment by akoe77** [comment]
+1

**Comment by Diethart** [comment]
Hey guys, 

I dunno if this still actual, but I found something that can help you. Check if you have any other breadcrumb's gem installed and remove it. In my case it was 'breadcrumbs_on_rails'. 

I suppose 'breadcrumbs' method from Gretel overridden by same method from another crumbs gem and this cause 'wrong number of arguments' error.

Hope it helps anyone who faced this problem.
