### ISSUE TITLE
Support if I18n

### ISSUE THREAD

**Issue by roba91** [lassebunk/gretel#84]
Does gretel support internationalization with I18n? If so this a small example could be added to the README.

**Comment by futhr** [comment]
Hi @roba91 this is quite trivial e.g.:

`config/breadcrumbs/backend.rb`

```rb
crumb :dashboard do
  link I18n.t(:dashboard), backend_dashboard_path
end
```

**Comment by roba91** [comment]
True. I opend this issue before really working with gretel. Not knowing, at that time, that all helpers are available in the crumb blocks.
