### ISSUE TITLE
Do not depend on "rails" gem, depend on parts of Rails that Gretel uses

### ISSUE THREAD

**Issue by adamniedzielski** [lassebunk/gretel#85]
### Description

Gretel specifies a dependency on `rails` gem - https://github.com/lassebunk/gretel/blob/8038a7cdd73dd4cc04a2c4020035a57241bd56d7/gretel.gemspec#L20

`rails` is just an "umbrella gem" that depends on all the components of Ruby on Rails framework - https://github.com/rails/rails/blob/86ca5b254109e64edeb6e142e656b8a8c247cac8/rails.gemspec - ActiveSupport, ActionPack, ActiveRecord, ...

I want to avoid installing `actioncable` gem in my Rails application. When Gretel specifies `rails` gem as a dependency then `actioncable` becomes my transitive dependency automatically and there is no way to avoid installing it.

### Proposal

Depend only on these parts of Rails that Gretel actually uses, for example:

```ruby
gem.add_dependency "railities", ">= 3.1.0"
gem.add_dependency "actionview", ">= 3.1.0"
```

I'm happy to make a PR if you accept the change.

**Comment by aleksandersumowski** [comment]
I've published gretel-lite gem with that single change:

https://rubygems.org/gems/gretel-lite/versions

You require it via:
`gem 'gretel-lite', require: "gretel"`

**Comment by MrShemek** [comment]
The issue was moved to the new repository: [link](https://github.com/WilHall/gretel/issues/7)
