### ISSUE TITLE
Specify class for link

### ISSUE THREAD

**Issue by morgant** [lassebunk/gretel#97]
Links in configuration file should support specifying a class. One can manually render the breadcrumbs to provide this functionality, but I feel this should be built-in, esp. considering you can specify classes for the breadcrumbs container and pre/post text.

**Comment by bananaappletw** [comment]
I want this feature too.
But this gem seems like not maintain anymore.

**Comment by mickro** [comment]
look at this fork `support-bootstrap4-alpha` branch: https://github.com/44uk/gretel/tree/support-bootstrap4-alpha

**Comment by MrShemek** [comment]
The issue was moved to the new repository: [link](https://github.com/WilHall/gretel/issues/10)
